### ISSUE TITLE
Limited no. of statuses in JSON returned from the search function 

### ISSUE THREAD

**Issue by ashendes** [wso2-ballerina/package-twitter#63]
**Description:**
The current search function doesn't have a parameter to specify the number of tweets required in the response so it returns the default amount which is quite limited.

**Related Issues:**
https://github.com/wso2-ballerina/package-twitter/issues/13

**Comment by Biruntha** [comment]
Fixed in [1].

[1] https://github.com/wso2-ballerina/package-twitter/pull/66

**Comment by anupama-pathirage** [comment]
Fixed with https://github.com/wso2-ballerina/package-twitter/pull/66 and hence closing the issue.
